-- Seed SQL generated from mind-data.js

INSERT OR REPLACE INTO categories (id, name, nsfw, sort_order) VALUES ('cat_1', 'Tools & Piracy', 0, 1);
INSERT OR REPLACE INTO groups (id, category_id, name, sort_order) VALUES ('grp_1_1', 'cat_1', 'Media & Downloads', 1);
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_1_1_1',
        'grp_1_1',
        'FMHY',
        'https://fmhy.net',
        'The biggest free media wiki',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/radarr.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        1
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_1_1_2',
        'grp_1_1',
        'Cobalt',
        'https://cobalt.tools/',
        'Download video & audio from anywhere',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/cobalt.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        2
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_1_1_3',
        'grp_1_1',
        'MAS',
        'https://massgrave.dev/',
        'Windows & Office activation scripts',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/archivebox.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        3
      );
INSERT OR REPLACE INTO groups (id, category_id, name, sort_order) VALUES ('grp_1_2', 'cat_1', 'Book & Paper Sources', 2);
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_1_2_1',
        'grp_1_2',
        'Anna''s Archive',
        'https://annas-archive.gl/',
        'Largest shadow library — books, papers, comics',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/booklogr-light.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        1
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_1_2_2',
        'grp_1_2',
        'Internet Archive',
        'https://archive.org/',
        'Borrow books, download old software & media',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/archivebox.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        2
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_1_2_3',
        'grp_1_2',
        'Open Library',
        'https://openlibrary.org/',
        'Free book borrowing, OpenLibrary catalogue',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/archivebox.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        3
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_1_2_4',
        'grp_1_2',
        'Sci-Hub',
        'https://sci-hub.ru/',
        'Free access to paywalled research papers',
        '',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        4
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_1_2_5',
        'grp_1_2',
        'LibGen',
        'https://libgen.li/',
        'Library Genesis — textbooks & fiction',
        '',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        5
      );
INSERT OR REPLACE INTO groups (id, category_id, name, sort_order) VALUES ('grp_1_3', 'cat_1', 'Recommended Subreddits', 3);
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_1_3_1',
        'grp_1_3',
        'r/privacy',
        'https://www.reddit.com/r/privacy/',
        'Reddit community for privacy news, tips, and discussions.',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/reddit.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        1
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_1_3_2',
        'grp_1_3',
        'r/selfhosted',
        'https://www.reddit.com/r/selfhosted/',
        'Reddit community for self-hosting apps, servers, and private clouds.',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/reddit.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        2
      );
INSERT OR REPLACE INTO categories (id, name, nsfw, sort_order) VALUES ('cat_2', 'Human Biology & Medicine', 0, 2);
INSERT OR REPLACE INTO groups (id, category_id, name, sort_order) VALUES ('grp_2_1', 'cat_2', 'Anatomy', 1);
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_2_1_1',
        'grp_2_1',
        'Institute of Human Anatomy',
        'https://youtube.com/channel/UCgBg0aacyJnw4qUnb1FlfEQ',
        'Real cadaver dissections, organ deep-dives',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/youtube.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        1
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_2_1_2',
        'grp_2_1',
        'Kenhub',
        'https://youtube.com/channel/UCHn_K1zOBYZqtmIYkXLEIQw',
        'Illustrated anatomy with quizzes',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/youtube.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        2
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_2_1_3',
        'grp_2_1',
        'Crash Course A&P',
        'https://youtube.com/playlist?list=PL8dPuuaLjXtOAKed_MxxWBNaPno5h3Zs8',
        'Full Anatomy & Physiology series',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/youtube.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        3
      );
INSERT OR REPLACE INTO groups (id, category_id, name, sort_order) VALUES ('grp_2_2', 'cat_2', 'Medicine & Physiology', 2);
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_2_2_1',
        'grp_2_2',
        'Ninja Nerd',
        'https://youtube.com/channel/UC6QYFutt9cluQ3uSM963_KQ',
        'Medical school-level physiology & pathology',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/youtube.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        1
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_2_2_2',
        'grp_2_2',
        'Najeeb Lectures',
        'https://www.youtube.com/@DrNajeebLectures',
        'Detailed medical & neuroscience lectures',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/youtube.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        2
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_2_2_3',
        'grp_2_2',
        'Osmosis',
        'https://www.youtube.com/@osmosis',
        'Clinical medicine, disease mechanisms',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/youtube.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        3
      );
INSERT OR REPLACE INTO groups (id, category_id, name, sort_order) VALUES ('grp_2_3', 'cat_2', 'Neuroscience', 3);
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_2_3_1',
        'grp_2_3',
        'MIT — The Human Brain',
        'https://youtube.com/playlist?list=PLUl4u3cNGP60IKRN_pFptIBxeiMc0MCJP',
        'Nancy Kanwisher — full MIT OCW course',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/youtube.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        1
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_2_3_2',
        'grp_2_3',
        'MIT — Human Behavioral Biology',
        'https://youtube.com/playlist?list=PL848F2368C90DDC3D',
        'Robert Sapolsky — biology of human behaviour',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/youtube.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        2
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_2_3_3',
        'grp_2_3',
        '3Blue1Brown — Neural Nets',
        'https://www.youtube.com/playlist?list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi',
        'Visual intuition for how neural networks work',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/youtube.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        3
      );
INSERT OR REPLACE INTO groups (id, category_id, name, sort_order) VALUES ('grp_2_4', 'cat_2', 'Books', 4);
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_2_4_1',
        'grp_2_4',
        'The Body',
        'https://annas-archive.gl/search?q=the+body+bill+bryson',
        'A tour of the human body for general readers',
        '',
        'book',
        'want',
        'Bill Bryson',
        '',
        '',
        '',
        0,
        '[]',
        1
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_2_4_2',
        'grp_2_4',
        'Behave',
        'https://annas-archive.gl/search?q=behave+sapolsky',
        'The biology of humans at our best and worst',
        '',
        'book',
        'reading',
        'Robert Sapolsky',
        '',
        '',
        '',
        0,
        '[]',
        2
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_2_4_3',
        'grp_2_4',
        'The Gene',
        'https://annas-archive.gl/search?q=the+gene+mukherjee',
        'An intimate history of genetics',
        '',
        'book',
        'want',
        'Siddhartha Mukherjee',
        '',
        '',
        '',
        0,
        '[]',
        3
      );
INSERT OR REPLACE INTO groups (id, category_id, name, sort_order) VALUES ('grp_2_5', 'cat_2', 'Documentaries & Shows', 5);
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_2_5_1',
        'grp_2_5',
        'Creation',
        'https://www.imdb.com/title/tt0974014/',
        'A biographical drama detailing Charles Darwin''s struggle to write ''On the Origin of Species'' while coping with family tragedy and religious conflict.',
        '',
        'media',
        'want',
        '',
        'Jon Amiel',
        '2009',
        'movie',
        0,
        '["Explores his grief over his daughter Annie''s death, his complex relationship with his devout wife Emma, and the paradigm-shifting science of natural selection.","Highlights the severe psychological and emotional toll the discovery had on Darwin before publication.","Starring Paul Bettany and Jennifer Connelly."]',
        1
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_2_5_2',
        'grp_2_5',
        'The Knick',
        'https://www.imdb.com/title/tt2933544/',
        'A medical drama set in early 20th-century New York, detailing the surgical breakthroughs and trials at The Knickerbocker Hospital.',
        '',
        'media',
        'want',
        '',
        'Steven Soderbergh',
        '2014',
        'show',
        0,
        '["Presents the historical development of pioneering surgeries, anesthesia, and medical technology in an era of high mortality rates.","Explores medical ethics, class dynamics, race relations, and drug addiction in late Gilded Age medicine.","Known for its visceral realism, directed by Steven Soderbergh and starring Clive Owen."]',
        2
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_2_5_3',
        'grp_2_5',
        'Planet Earth',
        'https://www.imdb.com/title/tt0795176/',
        'The landmark nature documentary series exploring the planet''s diverse biomes, ecosystems, and animal survival strategies.',
        '',
        'media',
        'watched',
        '',
        'Alastair Fothergill / BBC',
        '2006',
        'show',
        0,
        '["Narrated by Sir David Attenborough, utilizing pioneering high-definition filming techniques to capture rare animal behavior and remote landscapes.","Explores planetary biomes including mountains, fresh water, caves, deserts, ice worlds, plains, jungles, shallow seas, seasonal forests, and deep oceans.","Highlight of ecological and biological film-making showing complex animal adaptations."]',
        3
      );
INSERT OR REPLACE INTO categories (id, name, nsfw, sort_order) VALUES ('cat_3', 'Mind & Behaviour', 0, 3);
INSERT OR REPLACE INTO groups (id, category_id, name, sort_order) VALUES ('grp_3_1', 'cat_3', 'Psychology Courses', 1);
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_3_1_1',
        'grp_3_1',
        'Yale — Intro to Psychology',
        'https://youtube.com/playlist?list=PL6A08EB4EEFF3E91F',
        'Paul Bloom — full Yale course',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/youtube.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        1
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_3_1_2',
        'grp_3_1',
        'Ninja Nerd — Psychiatry',
        'https://www.youtube.com/@NinjaNerdScience',
        'DSM disorders, clinical psychiatry',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/youtube.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        2
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_3_1_3',
        'grp_3_1',
        'TED — The Paradox of Choice',
        'https://www.youtube.com/watch?v=VO6XEQIsCoM',
        'Barry Schwartz explains how choice overload increases anxiety and decreases satisfaction',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/youtube.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        3
      );
INSERT OR REPLACE INTO groups (id, category_id, name, sort_order) VALUES ('grp_3_2', 'cat_3', 'Psychotherapy & Mental Health', 2);
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_3_2_1',
        'grp_3_2',
        'Therapy in a Nutshell',
        'https://www.youtube.com/@TherapyinaNutshell',
        'CBT, anxiety, depression — practical tools',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/youtube.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        1
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_3_2_2',
        'grp_3_2',
        'Dr. Todd Grande',
        'https://www.youtube.com/@ToddGrande',
        'Personality disorders, forensic psychology',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/youtube.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        2
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_3_2_3',
        'grp_3_2',
        'TED — Quit Social Media',
        'https://www.youtube.com/watch?v=3E7hkPZ-HTk',
        'Cal Newport argues that social media is a commercial product, not a fundamental utility',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/youtube.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        3
      );
INSERT OR REPLACE INTO groups (id, category_id, name, sort_order) VALUES ('grp_3_3', 'cat_3', 'Documentaries & Movies', 3);
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_3_3_1',
        'grp_3_3',
        'The Century of the Self',
        'https://www.imdb.com/title/tt0432232/',
        'How those in power used Freud''s theories to control the crowd.',
        '',
        'media',
        'want',
        '',
        'Adam Curtis',
        '2002',
        'documentary',
        0,
        '[]',
        1
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_3_3_2',
        'grp_3_3',
        'Awakenings',
        'https://www.imdb.com/title/tt0099077/',
        'Based on Oliver Sacks'' biographical account of awakening catatonic patients.',
        '',
        'media',
        'want',
        '',
        'Penny Marshall',
        '1990',
        'movie',
        0,
        '[]',
        2
      );
INSERT OR REPLACE INTO groups (id, category_id, name, sort_order) VALUES ('grp_3_4', 'cat_3', 'Books', 4);
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_3_4_1',
        'grp_3_4',
        'Why Has Nobody Told Me This Before?',
        'https://annas-archive.gl/search?q=why+has+nobody+told+me+this+before',
        'Practical mental health tools from a therapist',
        '',
        'book',
        'want',
        'Dr. Julie Smith',
        '',
        '',
        '',
        0,
        '[]',
        1
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_3_4_2',
        'grp_3_4',
        'Thinking, Fast and Slow',
        'https://annas-archive.gl/search?q=thinking+fast+and+slow+kahneman',
        'How we actually make decisions (and why we''re wrong)',
        '',
        'book',
        'want',
        'Daniel Kahneman',
        '',
        '',
        '',
        0,
        '[]',
        2
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_3_4_3',
        'grp_3_4',
        'The Man Who Mistook His Wife for a Hat',
        'https://annas-archive.gl/search?q=man+who+mistook+his+wife+for+a+hat',
        'Neurological case studies — strange and moving',
        '',
        'book',
        'want',
        'Oliver Sacks',
        '',
        '',
        '',
        0,
        '[]',
        3
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_3_4_4',
        'grp_3_4',
        'Lost Connections',
        'https://annas-archive.gl/search?q=lost+connections+johann+hari',
        'The real causes of depression and anxiety',
        '',
        'book',
        'want',
        'Johann Hari',
        '',
        '',
        '',
        0,
        '[]',
        4
      );
INSERT OR REPLACE INTO categories (id, name, nsfw, sort_order) VALUES ('cat_4', 'Philosophy & Ethics', 0, 4);
INSERT OR REPLACE INTO groups (id, category_id, name, sort_order) VALUES ('grp_4_1', 'cat_4', 'Moral Philosophy', 1);
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_4_1_1',
        'grp_4_1',
        'Yale — Death (Shelly Kagan)',
        'https://youtube.com/playlist?list=PLEA18FAF1AD9047B0',
        'What is death, and should we fear it?',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/youtube.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        1
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_4_1_2',
        'grp_4_1',
        'Harvard — Justice (Michael Sandel)',
        'https://youtube.com/playlist?list=PL30C13C91CFFEFEA6',
        'What''s the right thing to do? Full course',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/youtube.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        2
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_4_1_3',
        'grp_4_1',
        'Michael Sugrue — Great Thinkers',
        'https://youtube.com/playlist?list=PL30RAv-0lkxGh5iMfRmZV8wEVeN50K06X',
        'Plato to Nietzsche — intellectual history',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/youtube.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        3
      );
INSERT OR REPLACE INTO groups (id, category_id, name, sort_order) VALUES ('grp_4_2', 'cat_4', 'Paradoxes & Thought Experiments', 2);
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_4_2_1',
        'grp_4_2',
        'Theseus Paradox',
        'https://en.wikipedia.org/wiki/Ship_of_Theseus',
        'A thought experiment raising the question of whether an object that has had all of its components replaced remains fundamentally the same object.',
        '',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '["Classic metaphysics and identity puzzle first documented by Plutarch.","Raises profound questions about physical continuity, formal vs. material cause, and the nature of selfhood.","Used as a metaphor in cognitive science, law, and literature to describe organizational and individual change."]',
        1
      );
INSERT OR REPLACE INTO groups (id, category_id, name, sort_order) VALUES ('grp_4_3', 'cat_4', 'Documentaries & Movies', 3);
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_4_3_1',
        'grp_4_3',
        'Ship of Theseus',
        'https://www.imdb.com/title/tt1773764/',
        'A highly acclaimed philosophical drama exploring questions of identity, justice, beauty, life, and death through three intersecting stories.',
        '',
        'media',
        'want',
        '',
        'Anand Gandhi',
        '2012',
        'movie',
        0,
        '["Follows a blind Egyptian photographer, an ailing monk fighting corporate animal testing, and a young stockbroker who receives a kidney transplant.","Directly references the classic Greek paradox, questioning personal boundaries, physical continuity, and moral responsibility.","Renowned for its stunning cinematography, philosophical depth, and intellectual independence."]',
        1
      );
INSERT OR REPLACE INTO groups (id, category_id, name, sort_order) VALUES ('grp_4_4', 'cat_4', 'Books', 4);
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_4_4_1',
        'grp_4_4',
        'Meditations',
        'https://annas-archive.gl/search?q=meditations+marcus+aurelius',
        'Stoic philosophy in private journal form',
        '',
        'book',
        'want',
        'Marcus Aurelius',
        '',
        '',
        '',
        0,
        '[]',
        1
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_4_4_2',
        'grp_4_4',
        'The Republic',
        'https://annas-archive.gl/search?q=the+republic+plato',
        'Justice, the ideal state, the allegory of the cave',
        '',
        'book',
        'want',
        'Plato',
        '',
        '',
        '',
        0,
        '[]',
        2
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_4_4_3',
        'grp_4_4',
        'Beyond Good and Evil',
        'https://annas-archive.gl/search?q=beyond+good+and+evil+nietzsche',
        'Critique of moral philosophy and truth',
        '',
        'book',
        'want',
        'Nietzsche',
        '',
        '',
        '',
        0,
        '[]',
        3
      );
INSERT OR REPLACE INTO categories (id, name, nsfw, sort_order) VALUES ('cat_5', 'Politics & Society', 0, 5);
INSERT OR REPLACE INTO groups (id, category_id, name, sort_order) VALUES ('grp_5_1', 'cat_5', 'Political Philosophy', 1);
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_5_1_1',
        'grp_5_1',
        'Yale — Political Philosophy',
        'https://youtube.com/playlist?list=PL8D95DEA9B7DFE825',
        'Steven Smith — Machiavelli to Tocqueville',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/youtube.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        1
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_5_1_2',
        'grp_5_1',
        'They Live — Sunglasses Scene',
        'https://www.youtube.com/watch?v=JI8AMRbqY6w',
        'The famous ideological reveal scene from John Carpenter''s ''They Live''',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/youtube.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        2
      );
INSERT OR REPLACE INTO groups (id, category_id, name, sort_order) VALUES ('grp_5_2', 'cat_5', 'Sociology & Culture', 2);
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_5_2_1',
        'grp_5_2',
        'Kurzgesagt',
        'https://www.youtube.com/@kurzgesagt',
        'Science & society explained beautifully',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/youtube.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        1
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_5_2_2',
        'grp_5_2',
        'Tom Nicholas',
        'https://www.youtube.com/@TomNicholas',
        'Critical theory, culture, politics — essay style',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/youtube.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        2
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_5_2_3',
        'grp_5_2',
        'Happiness',
        'https://www.youtube.com/watch?v=e9dZQelULDk',
        'Steve Cutts — A satirical short film about our search for happiness in a consumerist society',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/youtube.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        3
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_5_2_4',
        'grp_5_2',
        'The Story of Stuff',
        'https://www.youtube.com/watch?v=9GorqroigqM',
        'Annie Leonard — A fast-paced look at the underside of our production and consumption patterns',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/youtube.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        4
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_5_2_5',
        'grp_5_2',
        'The Employment (El Empleo)',
        'https://www.youtube.com/watch?v=5KyifKNlY7A',
        'Patricio Plaza & Santiago Grasso — An animated short film on the alienation of modern work',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/youtube.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        5
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_5_2_6',
        'grp_5_2',
        'MAN (2020)',
        'https://www.youtube.com/watch?v=DaFRheiGED0',
        'Steve Cutts — A look at man''s relationship with the natural world',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/youtube.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        6
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_5_2_7',
        'grp_5_2',
        'Like and Follow',
        'https://www.youtube.com/watch?v=ioaY1z2trx4',
        'Brent & Tobias — An animated short film about social media obsession and screen addiction',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/youtube.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        7
      );
INSERT OR REPLACE INTO groups (id, category_id, name, sort_order) VALUES ('grp_5_3', 'cat_5', 'Documentaries & Shows', 3);
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_5_3_1',
        'grp_5_3',
        'HyperNormalisation',
        'https://www.imdb.com/title/tt6156350/',
        'Explores how modern systems of power construct a fake, simplified version of the world.',
        '',
        'media',
        'want',
        '',
        'Adam Curtis',
        '2016',
        'documentary',
        0,
        '[]',
        1
      );
INSERT OR REPLACE INTO groups (id, category_id, name, sort_order) VALUES ('grp_5_4', 'cat_5', 'Books', 4);
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_5_4_1',
        'grp_5_4',
        'Sapiens',
        'https://annas-archive.gl/search?q=sapiens+harari',
        'A brief history of humankind',
        '',
        'book',
        'want',
        'Yuval Noah Harari',
        '',
        '',
        '',
        0,
        '[]',
        1
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_5_4_2',
        'grp_5_4',
        'The Origins of Totalitarianism',
        'https://annas-archive.gl/search?q=origins+of+totalitarianism+arendt',
        'How fascism and Stalinism arose',
        '',
        'book',
        'want',
        'Hannah Arendt',
        '',
        '',
        '',
        0,
        '[]',
        2
      );
INSERT OR REPLACE INTO groups (id, category_id, name, sort_order) VALUES ('grp_5_5', 'cat_5', 'Recommended Subreddits', 5);
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_5_5_1',
        'grp_5_5',
        'r/anticonsumption',
        'https://www.reddit.com/r/anticonsumption/',
        'Reddit community dedicated to criticizing and reducing consumerism and waste.',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/reddit.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        1
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_5_5_2',
        'grp_5_5',
        'r/anticonsumerism',
        'https://www.reddit.com/r/anticonsumerism/',
        'Reddit community sharing critiques, discussions, and articles on the impacts of corporate consumerism.',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/reddit.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        2
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_5_5_3',
        'grp_5_5',
        'r/simpleliving',
        'https://www.reddit.com/r/simpleliving/',
        'Reddit community focused on breaking free from the consumerist race and living more intentionally.',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/reddit.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        3
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_5_5_4',
        'grp_5_5',
        'r/marriagefree',
        'https://www.reddit.com/r/marriagefree/',
        'Reddit community discussing the choice to live without legal marriage or formal partnerships.',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/reddit.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        4
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_5_5_5',
        'grp_5_5',
        'r/childfree',
        'https://www.reddit.com/r/childfree/',
        'Reddit community for people who choose not to have children (childfree lifestyle).',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/reddit.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        5
      );
INSERT OR REPLACE INTO categories (id, name, nsfw, sort_order) VALUES ('cat_6', 'Economics & Game Theory', 0, 6);
INSERT OR REPLACE INTO groups (id, category_id, name, sort_order) VALUES ('grp_6_1', 'cat_6', 'Courses', 1);
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_6_1_1',
        'grp_6_1',
        'Yale — Financial Markets',
        'https://youtube.com/playlist?list=PL8FB14A2200B87185',
        'Robert Shiller — markets, risk, financial history',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/youtube.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        1
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_6_1_2',
        'grp_6_1',
        'Yale — Game Theory',
        'https://youtube.com/playlist?list=PL6EF60E1027E1A10B',
        'Ben Polak — Nash equilibria, auctions, strategy',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/youtube.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        2
      );
INSERT OR REPLACE INTO groups (id, category_id, name, sort_order) VALUES ('grp_6_2', 'cat_6', 'Books', 2);
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_6_2_1',
        'grp_6_2',
        'The Intelligent Investor',
        'https://annas-archive.gl/search?q=intelligent+investor+graham',
        'Classic value investing framework',
        '',
        'book',
        'want',
        'Benjamin Graham',
        '',
        '',
        '',
        0,
        '[]',
        1
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_6_2_2',
        'grp_6_2',
        'Misbehaving',
        'https://annas-archive.gl/search?q=misbehaving+thaler',
        'Behavioural economics — how humans actually decide',
        '',
        'book',
        'want',
        'Richard Thaler',
        '',
        '',
        '',
        0,
        '[]',
        2
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_6_2_3',
        'grp_6_2',
        'The Alchemy of Finance',
        'https://annas-archive.gl/search?q=alchemy+of+finance+soros',
        'Reflexivity theory, macro trading',
        '',
        'book',
        'want',
        'George Soros',
        '',
        '',
        '',
        0,
        '[]',
        3
      );
INSERT OR REPLACE INTO groups (id, category_id, name, sort_order) VALUES ('grp_6_3', 'cat_6', 'Documentaries & Movies', 3);
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_6_3_1',
        'grp_6_3',
        'The Imitation Game',
        'https://www.imdb.com/title/tt2084970/',
        'The historical drama of Alan Turing cracking the German Enigma code during World War II.',
        '',
        'media',
        'watched',
        '',
        'Morten Tyldum',
        '2014',
        'movie',
        0,
        '["Features Turing''s design and construction of the Christopher (bombe) machine to decode encrypted military radio messages.","Explores the origins of modern computer science, decision problems (Entscheidungsproblem), and artificial intelligence.","Highlights the tragic post-war prosecution of Turing for homosexuality, leading to his chemical castration and early death."]',
        1
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_6_3_2',
        'grp_6_3',
        'Ramanujan',
        'https://www.imdb.com/title/tt3110096/',
        'A biographical film tracking the life of the self-taught Indian mathematical genius Srinivasa Ramanujan.',
        '',
        'media',
        'want',
        '',
        'Gnana Rajasekaran',
        '2014',
        'movie',
        0,
        '["Details his early struggles in Tamil Nadu, his collaboration with G. H. Hardy at Trinity College, Cambridge, and his pioneering math theories.","Features mathematical concepts like partition formulas, modular forms, and the Ramanujan theta function.","Highlights the cultural clashes and intellectual hurdles faced by a self-taught genius in early 20th-century academia."]',
        2
      );
INSERT OR REPLACE INTO categories (id, name, nsfw, sort_order) VALUES ('cat_7', 'Physics & Cosmology', 0, 7);
INSERT OR REPLACE INTO groups (id, category_id, name, sort_order) VALUES ('grp_7_1', 'cat_7', 'Courses & Channels', 1);
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_7_1_1',
        'grp_7_1',
        'Sean Carroll — Biggest Ideas',
        'https://youtube.com/playlist?list=PLrxfgDEc2NxZJcWcrxH3jyjUUrJlnoyzX',
        'Quantum mechanics, spacetime, entropy',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/youtube.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        1
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_7_1_2',
        'grp_7_1',
        'PBS Space Time',
        'https://www.youtube.com/@pbsspacetime',
        'Graduate-level physics — dark matter, black holes',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/youtube.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        2
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_7_1_3',
        'grp_7_1',
        'Veritasium',
        'https://www.youtube.com/@veritasium',
        'Physics, science, and surprising ideas',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/youtube.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        3
      );
INSERT OR REPLACE INTO groups (id, category_id, name, sort_order) VALUES ('grp_7_2', 'cat_7', 'Documentaries & Movies', 2);
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_7_2_1',
        'grp_7_2',
        'Cosmos: A Spacetime Odyssey',
        'https://www.imdb.com/title/tt2395695/',
        'An adventure science series exploring the universe, space, time, and biology.',
        '',
        'media',
        'watched',
        '',
        'Neil deGrasse Tyson',
        '2014',
        'show',
        0,
        '[]',
        1
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_7_2_2',
        'grp_7_2',
        'Cosmos: Possible Worlds',
        'https://www.imdb.com/title/tt11170862/',
        'An adventure science series exploring the universe, space, time, and biology.',
        '',
        'media',
        'watched',
        '',
        'Neil deGrasse Tyson',
        '2020',
        'show',
        0,
        '[]',
        2
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_7_2_3',
        'grp_7_2',
        'Cosmos: A Personal Voyage',
        'https://www.imdb.com/title/tt0081846/',
        'The landmark documentary series exploring astronomical phenomena and our place in the universe.',
        '',
        'media',
        'want',
        '',
        'Carl Sagan',
        '1980',
        'show',
        0,
        '[]',
        3
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_7_2_4',
        'grp_7_2',
        'Interstellar',
        'https://www.imdb.com/title/tt0816692/',
        'A science fiction epic with highly accurate depictions of black holes and relativity.',
        '',
        'media',
        'watched',
        '',
        'Christopher Nolan',
        '2014',
        'movie',
        0,
        '[]',
        4
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_7_2_5',
        'grp_7_2',
        'Genius',
        'https://www.imdb.com/title/tt5673782/',
        'An anthology series charting the personal and professional lives of history''s most brilliant innovators.',
        '',
        'media',
        'watched',
        '',
        'National Geographic',
        '2017',
        'show',
        0,
        '["Season 1 focuses on the life and breakthroughs of physicist Albert Einstein, adapted from Walter Isaacson''s biography.","Subsequent seasons explore other icons of creativity and intellect including Pablo Picasso, Aretha Franklin, and Mary Shelley.","Captures both the rigorous intellectual struggle and the messy personal lives of these monumental figures."]',
        5
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_7_2_6',
        'grp_7_2',
        'Leonardo',
        'https://www.imdb.com/title/tt9146528/',
        'A historical drama series exploring the extraordinary mind, achievements, and hidden secrets of Leonardo da Vinci.',
        '',
        'media',
        'watched',
        '',
        'Frank Spotnitz',
        '2021',
        'show',
        0,
        '["Fictionalizes and explores the story behind Leonardo''s greatest artistic creations like the Mona Lisa and the Last Supper.","Features his engineering blueprints, anatomy sketches, and creative philosophy of uniting art with science.","Co-production starring Aidan Turner, highlighting Renaissance politics and Florence/Milan court life."]',
        6
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_7_2_7',
        'grp_7_2',
        'Isaac Newton: The Last Magician',
        'https://www.imdb.com/title/tt2929452/',
        'A compelling docudrama exploring Isaac Newton''s obsession with alchemy, biblical prophecy, and the occult.',
        '',
        'media',
        'want',
        '',
        'Renny Bartlett / BBC',
        '2013',
        'movie',
        0,
        '["Based on Newton''s private notebooks, revealing his secret, illegal theological beliefs and alchemical recipes.","Examines the duality of the father of modern calculus and gravity who also spent decades seeking the philosopher''s stone.","Features expert interviews alongside dramatic reconstructions of his reclusive life in Cambridge."]',
        7
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_7_2_8',
        'grp_7_2',
        'Einstein''s Quantum Riddle',
        'https://www.imdb.com/title/tt9622956/',
        'Physicists test Einstein''s ''spooky action at a distance'' using light from distant quasars to study quantum entanglement.',
        '',
        'media',
        'want',
        '',
        'PBS Nova',
        '2019',
        'show',
        0,
        '["Explores the concepts of quantum entanglement, Bell''s inequality, and the historic Einstein-Podolsky-Rosen (EPR) paradox.","Shows how modern researchers use ancient light from across the universe to rule out local hidden variables.","Covers the potential applications of quantum mechanics in secure communication and quantum computing."]',
        8
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_7_2_9',
        'grp_7_2',
        'Chernobyl',
        'https://www.imdb.com/title/tt8162428/',
        'A dramatization of the 1986 nuclear disaster at the Chernobyl Power Plant, focusing on the human cost and the search for truth.',
        '',
        'media',
        'watched',
        '',
        'Craig Mazin',
        '2019',
        'show',
        0,
        '["Explores the nuclear physics of an RBMK reactor, the mechanics of a steam explosion, and the severe effects of ionizing radiation.","Examines the political and bureaucratic failures, secret state security pressure, and the courage of liquidators and scientists.","Highlights the crucial quote: ''What is the cost of lies?''"]',
        9
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_7_2_10',
        'grp_7_2',
        'Franklin',
        'https://www.imdb.com/title/tt18359702/',
        'A mini-series exploring Benjamin Franklin''s critical diplomatic and scientific influence in France during the American Revolution.',
        '',
        'media',
        'want',
        '',
        'Kirk Ellis',
        '2024',
        'show',
        0,
        '["Depicts Franklin''s status as a world-renowned natural philosopher and electrical physicist alongside his espionage maneuvers.","Highlights the court politics of Versailles and negotiations for the Franco-American alliance.","Starring Michael Douglas as the legendary polymath."]',
        10
      );
INSERT OR REPLACE INTO groups (id, category_id, name, sort_order) VALUES ('grp_7_3', 'cat_7', 'Books', 3);
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_7_3_1',
        'grp_7_3',
        'A Brief History of Time',
        'https://annas-archive.gl/search?q=brief+history+of+time+hawking',
        'Cosmology for the general reader',
        '',
        'book',
        'want',
        'Stephen Hawking',
        '',
        '',
        '',
        0,
        '[]',
        1
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_7_3_2',
        'grp_7_3',
        'The Fabric of Reality',
        'https://annas-archive.gl/search?q=fabric+of+reality+deutsch',
        'Quantum physics and the nature of existence',
        '',
        'book',
        'want',
        'David Deutsch',
        '',
        '',
        '',
        0,
        '[]',
        2
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_7_3_3',
        'grp_7_3',
        'Something Deeply Hidden',
        'https://annas-archive.gl/search?q=something+deeply+hidden+carroll',
        'Many-worlds quantum mechanics',
        '',
        'book',
        'want',
        'Sean Carroll',
        '',
        '',
        '',
        0,
        '[]',
        3
      );
INSERT OR REPLACE INTO categories (id, name, nsfw, sort_order) VALUES ('cat_8', 'Sex, Intimacy & Relationships', 1, 8);
INSERT OR REPLACE INTO groups (id, category_id, name, sort_order) VALUES ('grp_8_1', 'cat_8', 'Sexual Health & Education', 1);
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_8_1_1',
        'grp_8_1',
        'Bad Girls Bible',
        'https://badgirlsbible.com',
        'Practical intimacy guides',
        '',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        1
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_8_1_2',
        'grp_8_1',
        'Beducated',
        'https://beducated.com/',
        'Structured sexual education courses',
        '',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        2
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_8_1_3',
        'grp_8_1',
        'OMGyes',
        'https://1337x.to/torrent/4817917/OMGyes-com-The-Science-of-Women-s-Pleasure/',
        'The Science of Women''s Pleasure (Torrent)',
        '',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '["An interactive platform containing video interviews, research findings, and graphic animations detailing women''s sexual pleasure.","Focuses on specific techniques (e.g., ''staging'', ''edging'', ''framing'') backed by research from Indiana University.","Highly recommended for understanding sexual physiology and intimate communication."]',
        3
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_8_1_4',
        'grp_8_1',
        'Scarleteen',
        'https://www.scarleteen.com/',
        'Inclusive, progressive, and honest sexual health and relationships info for teens and young adults',
        '',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '["An inclusive, progressive sex education resource founded in 1998 by Heather Corinna.","Outstanding sections on relationship dynamics, boundary negotiation, consent, and LGBTQ+ sexual health.","Excellent message boards and direct support services for teens and young adults."]',
        4
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_8_1_5',
        'grp_8_1',
        'Amaze',
        'https://amaze.org/',
        'Age-appropriate resources covering puberty, reproduction, relationships, and health',
        '',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        5
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_8_1_6',
        'grp_8_1',
        'Sense',
        'https://sense.info/',
        'A comprehensive guide on sexuality, contraception, relationships, and body image',
        '',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        6
      );
INSERT OR REPLACE INTO groups (id, category_id, name, sort_order) VALUES ('grp_8_2', 'cat_8', 'Shibari & Rope Bondage', 2);
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_8_2_1',
        'grp_8_2',
        'Crash Restraint',
        'https://crash-restraint.com/',
        'Technique library, safety guides, structured learning',
        '',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        1
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_8_2_2',
        'grp_8_2',
        'The Duchy',
        'https://thedutchy.com/',
        'Shibari community, tutorials, artist profiles',
        '',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        2
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_8_2_3',
        'grp_8_2',
        'Rory''s Brainworks',
        'https://www.youtube.com/@RorysBrainworks',
        'Shibari tutorials — clear and methodical',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/youtube.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        3
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_8_2_4',
        'grp_8_2',
        'Bondage Tuition',
        'https://www.youtube.com/@BondageTuition',
        'Step-by-step rope bondage instruction',
        'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/youtube.png',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        4
      );
INSERT OR REPLACE INTO groups (id, category_id, name, sort_order) VALUES ('grp_8_3', 'cat_8', 'Documentaries & Shows', 3);
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_8_3_1',
        'grp_8_3',
        'The Principles of Pleasure',
        'https://www.imdb.com/title/tt18299058/',
        'A celebration of female pleasure and modern sexual education.',
        '',
        'media',
        'watched',
        '',
        'Michelle Buteau / Netflix',
        '2022',
        'show',
        0,
        '[]',
        1
      );
INSERT OR REPLACE INTO groups (id, category_id, name, sort_order) VALUES ('grp_8_4', 'cat_8', 'Books', 4);
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_8_4_1',
        'grp_8_4',
        'The Ethical Slut',
        'https://annas-archive.gl/search?index=&page=1&sort=&display=&q=The+Ethical+Slut+third',
        'The foundational guide to ethical non-monogamy',
        '',
        'book',
        'read',
        'Dossie Easton & Janet Hardy',
        '',
        '',
        '',
        0,
        '[]',
        1
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_8_4_2',
        'grp_8_4',
        'The Ethical Slut Workbook',
        'https://annas-archive.gl/search?index=&page=1&sort=&display=&q=The+Ethical+Slut+Workbook',
        'Companion exercises for the main book',
        '',
        'book',
        'want',
        'Dossie Easton & Janet Hardy',
        '',
        '',
        '',
        0,
        '[]',
        2
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_8_4_3',
        'grp_8_4',
        'She Comes First',
        'https://annas-archive.gl/search?q=9780060538262',
        'A guide for couples on female pleasure',
        '',
        'book',
        'read',
        'Ian Kerner',
        '',
        '',
        '',
        0,
        '[]',
        3
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_8_4_4',
        'grp_8_4',
        'Come as You Are',
        'https://annas-archive.gl/search?q=1982165316',
        'The science of female sexuality',
        '',
        'book',
        'read',
        'Emily Nagoski',
        '',
        '',
        '',
        0,
        '[]',
        4
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_8_4_5',
        'grp_8_4',
        'Mating in Captivity',
        'https://annas-archive.gl/search?q=mating+in+captivity+esther+perel',
        'Desire and intimacy in long-term relationships',
        '',
        'book',
        'want',
        'Esther Perel',
        '',
        '',
        '',
        0,
        '[]',
        5
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_8_4_6',
        'grp_8_4',
        'The State of Affairs',
        'https://annas-archive.gl/search?q=state+of+affairs+esther+perel',
        'Rethinking infidelity',
        '',
        'book',
        'want',
        'Esther Perel',
        '',
        '',
        '',
        0,
        '[]',
        6
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_8_4_7',
        'grp_8_4',
        'Shibari: Everything you want to know about Japanese bondage. Guide in pictures.',
        'https://annas-archive.gl/search?index=&page=1&sort=&display=&q=Shibari++Seito+Saiki',
        'A comprehensive introduction to Shibari from a master rigger',
        '',
        'book',
        'read',
        'Seito Saiki',
        '',
        '',
        '',
        0,
        '[]',
        7
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_8_4_8',
        'grp_8_4',
        'Shibari You Can Use',
        'https://annas-archive.gl/search?q=shibari+you+can+use+harrington',
        'Practical rope bondage with technique photos',
        '',
        'book',
        'reading',
        'Lee Harrington',
        '',
        '',
        '',
        0,
        '[]',
        8
      );
INSERT OR REPLACE INTO categories (id, name, nsfw, sort_order) VALUES ('cat_9', 'Topics to Explore', 0, 9);
INSERT OR REPLACE INTO groups (id, category_id, name, sort_order) VALUES ('grp_9_1', 'cat_9', 'Concepts & Notes', 1);
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_9_1_1',
        'grp_9_1',
        'Ethical / Sex-Positive Pornography',
        'https://en.wikipedia.org/wiki/Feminist_pornography',
        'Pornography produced under ethical labor standards with an emphasis on mutual consent, diverse body representation, and authentic pleasure.',
        '',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '["Prioritizes fair wages, transparent contracts, and safe working conditions for all adult performers.","Focuses on a wider range of body types, sexual orientations, gender identities, and realistic expressions of pleasure.","Contrasts with mainstream industrial pornography, which often relies on performative or aggressive tropes.","Key feminist and sex-positive directors/creators include Erika Lust, CrashPad Series, and Petra Joy."]',
        1
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_9_1_2',
        'grp_9_1',
        'Gender Studies',
        'https://en.wikipedia.org/wiki/Gender_studies',
        'An interdisciplinary academic field analyzing gender identity and representation across society, law, history, and literature.',
        '',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '["Examines how gender roles, expectations, and biological sex are socially and historically constructed.","Investigates the intersection of gender with other power structures like race, class, ethnicity, and sexuality.","Includes key theoretical frameworks such as Judith Butler''s theory of gender performativity.","Essential texts and thinkers include Simone de Beauvoir (The Second Sex) and bell hooks (Feminist Theory: From Margin to Center)."]',
        2
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_9_1_3',
        'grp_9_1',
        'Vipassana Meditation',
        'https://en.wikipedia.org/wiki/Vipassana',
        'An ancient Indian mindfulness meditation technique focused on insight into the true nature of reality.',
        '',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '["The term translates to ''insight'' or ''clear-seeing'' into the impermanent nature of mind and body.","Emphasizes rigorous self-observation and training the mind to observe physical sensations equanimously without reacting.","Typically learned through a standardized 10-day residential silent course taught globally under the guidance of S. N. Goenka.","Focuses on dissolving mental conditioning and attachments to achieve inner peace and liberation."]',
        3
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_9_1_4',
        'grp_9_1',
        'Tantric Sex & Yoni Massage',
        'https://en.wikipedia.org/wiki/Neotantra',
        'Ancient and modern intimate practices focusing on mindful presence, deep connection, and conscious genital touch.',
        '',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '["Rooted in neo-tantra, placing an emphasis on conscious breathing, sensory awareness, and spiritual union rather than goal-oriented climax.","Yoni massage (yoni meaning ''sacred temple'' in Sanskrit) is approached as a slow, non-demanding touch session to help release emotional trauma or physical tension.","Absolutely requires clear boundaries, ongoing active consent, and a safe, performance-free environment.","Focuses on healing, exploration of somatic sensation, and expanding body pleasure map."]',
        4
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_9_1_5',
        'grp_9_1',
        'Lucid Dreaming',
        'https://en.wikipedia.org/wiki/Lucid_dream',
        'The state of becoming consciously aware that you are dreaming while inside the dream, enabling influence over its events.',
        '',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '["Occurs predominantly during the REM (Rapid Eye Movement) stage of sleep where brain activity is high.","Common induction techniques include MILD (Mnemonic Induction), WILD (Wake-Initiated), and performing daytime reality checks.","Used for creative ideation, nightmare therapy, motor skill practice, and exploring the boundaries of consciousness."]',
        5
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_9_1_6',
        'grp_9_1',
        'Ophthalmology Basics (Cataracts & Glaucoma)',
        'https://en.wikipedia.org/wiki/Ophthalmology',
        'Fundamental eye anatomy and key clinical vision disorders involving lens clouding and optic nerve damage.',
        '',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '["Cataracts: Progressive clouding of the eye''s natural crystalline lens, leading to blurry vision, glare sensitivity, and treated via surgical lens replacement.","Glaucoma: Optic nerve damage caused by inadequate fluid drainage and high intraocular pressure (IOP), causing irreversible vision loss if unchecked.","Diagnosis involves checking intraocular pressure (Tonometry) and direct inspection of the optic nerve head (Ophthalmoscopy)."]',
        6
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_9_1_7',
        'grp_9_1',
        'Psychological First Aid (PFA)',
        'https://en.wikipedia.org/wiki/Psychological_first_aid',
        'An evidence-informed modular framework for assisting people in the immediate aftermath of disaster or trauma.',
        '',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '["Designed to reduce initial distress, encourage adaptive coping, and establish connection to resources.","Structured around three simple action principles: Look (check for safety/needs), Listen (active, non-intrusive listening), and Link (connecting to loved ones/practical aid).","Does not pathologize distress or force verbal processing; focuses on basic comfort, safety, and stabilization."]',
        7
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_9_1_8',
        'grp_9_1',
        'Maslow''s Hierarchy & Cognitive Paradoxes',
        'https://en.wikipedia.org/wiki/Maslow''s_hierarchy_of_needs',
        'Core motivational psychological models and mental rules explaining human behavior and group choices.',
        '',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '["Maslow''s Hierarchy: A five-tier pyramid of human needs spanning physiological, safety, social, esteem, and self-actualization.","Parkinson''s Law: The observation that work expands to fill the time allocated for its completion, promoting artificial complexity.","Abilene Paradox: A collective decision-making error where a group agrees on a course of action that no individual wants, due to a perceived expectation of conformity."]',
        8
      );
INSERT OR REPLACE INTO groups (id, category_id, name, sort_order) VALUES ('grp_9_2', 'cat_9', 'Language Learning', 2);
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_9_2_1',
        'grp_9_2',
        'Spanish (Speaking)',
        'https://en.wikipedia.org/wiki/Spanish_language',
        'Focused on developing conversational Spanish fluency, pronunciation, and basic speaking capabilities.',
        '',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '["Focus on high-frequency conversational patterns, daily vocabulary, and verb conjugations in active speaking.","Emphasis on accurate pronunciation including the trilled ''rr'', soft ''d'', and silent ''h''.","Leverages immersion techniques, conversational podcasts, and active recall practice."]',
        1
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_9_2_2',
        'grp_9_2',
        'Urdu (Writing)',
        'https://en.wikipedia.org/wiki/Urdu_alphabet',
        'Focused on mastering the Urdu alphabet and the elegant Nastaliq calligraphic writing script.',
        '',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '["Learning the Nastaliq calligraphy style of the Perso-Arabic script.","Mastering the 39 basic Urdu letters and their changing initial, medial, and final forms when joined.","Practicing right-to-left stroke mechanics, dot placements (nuqtas), and complex ligatures."]',
        2
      );
INSERT OR REPLACE INTO categories (id, name, nsfw, sort_order) VALUES ('cat_10', 'Board & Card Games', 0, 10);
INSERT OR REPLACE INTO groups (id, category_id, name, sort_order) VALUES ('grp_10_1', 'cat_10', 'Board & Card Games', 1);
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_10_1_1',
        'grp_10_1',
        'DIXIT',
        'https://boardgamegeek.com/boardgame/39856/dixit',
        'An award-winning creative storytelling card game of imagination, subtle clues, and beautifully illustrated dreamlike cards.',
        '',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '["Basic Description: A creative party game where players use gorgeous, surreal illustrations to bluff their opponents and guess which card matches the story teller''s clue.","Where to Buy / Play: Purchase on Amazon or local board game stores. Play online via Board Game Arena (boardgamearena.com).","Rules & Setup: Each player holds a hand of cards with unique illustrations. One player is the storyteller, who says a word or phrase describing one of their cards. Other players choose a card from their own hand that best matches the description. All chosen cards are shuffled and revealed, and players vote on which card was the storyteller''s."]',
        1
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_10_1_2',
        'grp_10_1',
        'Exploding Kittens',
        'https://explodingkittens.com/',
        'A highly strategic, kitty-powered version of Russian Roulette card game with defusal cards and targeted attacks.',
        '',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '["Basic Description: A fast-paced card game where players draw cards until someone draws an Exploding Kitten, at which point they explode and are out of the game.","Where to Buy / Play: Buy from explodingkittens.com or Amazon. Play online via the mobile app (iOS/Android).","Rules & Setup: Players take turns drawing cards from the deck. Play cards to skip, attack, see the future, or shuffle to avoid drawing."]',
        2
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_10_1_3',
        'grp_10_1',
        'UNO & UNO Flip',
        'https://www.unoflip.org/',
        'The classic matching color and number card game, along with its intense double-sided ''Flip'' variant.',
        '',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '["Basic Description: UNO is the famous card shedding game. UNO Flip adds a double-sided deck with a ''Dark Side'' featuring harsher action cards.","Rules & Setup: Match colors and numbers. In UNO Flip, playing a ''Flip'' card turns all cards over from the Light Side to the Dark Side."]',
        3
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_10_1_4',
        'grp_10_1',
        'Speed Cubing',
        'https://jperm.net/',
        'The sport of solving a Rubik''s Cube and other twisty puzzles as quickly as possible, utilizing optimized algorithms.',
        '',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '["Basic Description: Solving 3x3x3 Rubik''s Cubes using speed-solving methods. JPerm (jperm.net) is the premier learning resource.","Key Methods: CFOP (Cross, F2L, OLL, PLL) is the most popular speedsolving method."]',
        4
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_10_1_5',
        'grp_10_1',
        'Cardistry',
        'https://www.reddit.com/r/cardistry/',
        'The non-magical performance art of handling playing cards with dexterity, creative flourishes, and visual flow.',
        '',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '["Basic Description: Performance art focused on card manipulation, shuffles, cuts, fans, and aerials.","Fundamentals: Charlier Cut, Revolution Cut, Sybil Cut, Spring, and Giant Fan."]',
        5
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_10_1_6',
        'grp_10_1',
        'SEQUENCE',
        'https://boardgamegeek.com/boardgame/2375/sequence',
        'A board and card game combo where players build lines of five connected chips on the board matching cards from their hand.',
        '',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '["Basic Description: Tactical board game played with chips and a deck of cards to place five chips in a row."]',
        6
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_10_1_7',
        'grp_10_1',
        'Swacardz',
        'https://swacardz.com/',
        'A fast-paced tactical physical card-combustion game where cards are tossed, flipped, and swiped in active dueling.',
        '',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '[]',
        7
      );
INSERT OR REPLACE INTO items (id, group_id, name, href, description, icon, type, status, author, creator, year, media_type, nsfw, notes_json, sort_order) VALUES (
        'item_10_1_8',
        'grp_10_1',
        'Open Bottle Close Bottle',
        'https://en.wikipedia.org/wiki/Mind_game',
        'An intriguing, mysterious interactive party trick game involving hand movements and a hidden deductive rule.',
        '',
        'link',
        '',
        '',
        '',
        '',
        '',
        0,
        '["Hidden Rule: Determined entirely by whether the host''s legs or ankles are crossed (closed) or uncrossed/apart (open) at the moment of asking."]',
        8
      );
